name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - name: Install Node
        uses: actions/checkout@v3
        with:
          node-version : '17.x'

      - name: Install Newman
        run: npm install -g newman

      - name: Run collection
        run: newman run trello/test_collection.json -e test_environment.json
